services:
  # --- Frontend (หน้าเว็บลูกค้า) ---
  web:
    build:
      context: ./web-game-laos
      dockerfile: ./web-game-laos/Dockerfile.prod
    ports:
      - "80:80" # เข้าผ่าน http://localhost
    restart: always
    depends_on:
      - api
    env_file: .env
    networks:
      - prod-network

  # --- Admin Dashboard ---
  dashboard:
    build:
      context: ./dashboard-game
      dockerfile: ./dashboard-game/Dockerfile.prod
    ports:
      - "8080:80" # เข้าผ่าน http://localhost:8080
    restart: always
    depends_on:
      - api
    env_file: .env
    networks:
      - prod-network

networks:
  prod-network:
    driver: bridge
